export const CHANGE_USER = 'CHANGE_USER';

export const QUESTIONS_LOADED = 'QUESTIONS_LOADED';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const CHANGE_QUESTION = 'CHANGE_QUESTION';
export const QUESTIONS_LOADING_ERROR = 'QUESTIONS_LOADING_ERROR';

export const DATABASE_LOADING = 'DATABASE_LOADING';
export const DATABASE_LOADED = 'DATABASE_LOADED';
export const CHANGE_TABLE_ACTIVITY = 'CHANGE_TABLE_ACTIVITY';

export const PIN_INPUT_AREA = 'PIN_INPUT_AREA';
export const CREATE_NEW_TAB = 'CREATE_NEW_TAB';
export const CHANGE_TAB = 'CHANGE_TAB';
export const DELETE_TAB = 'DELETE_TAB';
export const DELETE_ALL_TABS = 'DELETE_ALL_TABS';
export const CHANGE_TAB_RESPONSE = 'CHANGE_TAB_RESPONSE';
export const CHANGE_TAB_HTML = 'CHANGE_TAB_HTML';
