export const CHANGE_USER = 'CHANGE_USER';

// questions contants
export const QUESTIONS_LOADED = 'QUESTIONS_LOADED';
export const TEST_META_LOADED = 'TEST_META_LOADED';
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const CHANGE_QUESTION = 'CHANGE_QUESTION';
export const CHANGE_QUESTION_STATUS = 'CHANGE_QUESTION_STATUS';
export const QUESTIONS_LOADING_ERROR = 'QUESTIONS_LOADING_ERROR';
export const CHANGE_SOLVED_QUESTION_SQL = 'CHANGE_SOLVED_QUESTION_SQL';
export const SQL_CHECKING = 'SQL_CHECKING';
export const CHANGE_ALL_QUESTIONS_VISIBILITY = 'questions/ALL_QUESTIONS_VISIBILITY';

// database contants
export const DATABASE_LOADING = 'DATABASE_LOADING';
export const DATABASE_LOADED = 'DATABASE_LOADED';
export const CHANGE_TABLE_ACTIVITY = 'CHANGE_TABLE_ACTIVITY';

// tabs contants
export const PIN_INPUT_AREA = 'PIN_INPUT_AREA';
export const CREATE_NEW_TAB = 'CREATE_NEW_TAB';
export const CREATE_INITIAL_TABS = 'CREATE_INITIAL_TABS';
export const CHANGE_TAB = 'CHANGE_TAB';
export const DELETE_TAB = 'DELETE_TAB';
export const DELETE_ALL_TABS = 'DELETE_ALL_TABS';
export const CHANGE_TAB_RESPONSE = 'CHANGE_TAB_RESPONSE';
export const CHANGE_TAB_HTML = 'CHANGE_TAB_HTML';
export const CHANGE_SQL_RESPONSE_TYPE = 'CHANGE_SQL_RESPONSE_TYPE';

// test contants
export const CHANGE_COMPLETED_POPUP_VISIBILITY = 'CHANGE_COMPLETED_POPUP_VISIBILITY';
export const CHANGE_LOADER_VISIBILITY = 'CHANGE_LOADER_VISIBILITY';
export const CHANGE_TEST_STATUS = 'CHANGE_TEST_STATUS';
export const LOADER_ERROR = 'LOADER_ERROR';
export const CHANGE_TEST_TIMESTAMP = 'CHANGE_TEST_TIMESTAMP';
export const RESET_TEST = 'RESET_TEST';

// notification constants
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';

// settings constants
export const CHANGE_EDITOR_THEME = 'CHANGE_EDITOR_THEME';
